// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveConnection dco_decode_active_connection(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ConnectionInfo dco_decode_connection_info(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LatencyTestResult dco_decode_latency_test_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActiveConnection> dco_decode_list_active_connection(dynamic raw);

  @protected
  List<ConnectionInfo> dco_decode_list_connection_info(dynamic raw);

  @protected
  List<LatencyTestResult> dco_decode_list_latency_test_result(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, int)> dco_decode_list_record_string_u_16(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  ProxyStatus dco_decode_proxy_status(dynamic raw);

  @protected
  (String, int) dco_decode_record_string_u_16(dynamic raw);

  @protected
  (BigInt, BigInt, BigInt, BigInt) dco_decode_record_u_64_u_64_u_64_u_64(
    dynamic raw,
  );

  @protected
  (BigInt, BigInt, BigInt, BigInt, BigInt, BigInt)
  dco_decode_record_u_64_u_64_u_64_u_64_usize_usize(dynamic raw);

  @protected
  SystemInfo dco_decode_system_info(dynamic raw);

  @protected
  TrafficStats dco_decode_traffic_stats(dynamic raw);

  @protected
  TunStatus dco_decode_tun_status(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveConnection sse_decode_active_connection(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ConnectionInfo sse_decode_connection_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LatencyTestResult sse_decode_latency_test_result(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActiveConnection> sse_decode_list_active_connection(
    SseDeserializer deserializer,
  );

  @protected
  List<ConnectionInfo> sse_decode_list_connection_info(
    SseDeserializer deserializer,
  );

  @protected
  List<LatencyTestResult> sse_decode_list_latency_test_result(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, int)> sse_decode_list_record_string_u_16(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ProxyStatus sse_decode_proxy_status(SseDeserializer deserializer);

  @protected
  (String, int) sse_decode_record_string_u_16(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt, BigInt, BigInt) sse_decode_record_u_64_u_64_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt, BigInt, BigInt, BigInt, BigInt)
  sse_decode_record_u_64_u_64_u_64_u_64_usize_usize(
    SseDeserializer deserializer,
  );

  @protected
  SystemInfo sse_decode_system_info(SseDeserializer deserializer);

  @protected
  TrafficStats sse_decode_traffic_stats(SseDeserializer deserializer);

  @protected
  TunStatus sse_decode_tun_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_connection(
    ActiveConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_connection_info(
    ConnectionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_latency_test_result(
    LatencyTestResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_active_connection(
    List<ActiveConnection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_connection_info(
    List<ConnectionInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_latency_test_result(
    List<LatencyTestResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_u_16(
    List<(String, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_status(ProxyStatus self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_u_16(
    (String, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64_u_64_u_64(
    (BigInt, BigInt, BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64_u_64_u_64_usize_usize(
    (BigInt, BigInt, BigInt, BigInt, BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_system_info(SystemInfo self, SseSerializer serializer);

  @protected
  void sse_encode_traffic_stats(TrafficStats self, SseSerializer serializer);

  @protected
  void sse_encode_tun_status(TunStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
